# Generated by Django 5.2.5 on 2025-08-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocalFilePosition',
            fields=[
                ('global_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.file')),
                ('file_hash', models.CharField(max_length=300)),
                ('file_id', models.IntegerField()),
                ('client_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.client')),
            ],
        ),
    ]
