# Generated by Django 5.2.5 on 2025-08-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfileposition',
            name='global_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_file_position', serialize=False, to='menu.file'),
        ),
    ]
