# Generated by Django 5.2.5 on 2025-08-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_localfileposition_global_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalFilePosition',
        ),
    ]
