# Generated by Django 5.2.5 on 2025-08-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_delete_localfileposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFilePosition',
            fields=[
                ('file_hash', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('file_id', models.IntegerField()),
                ('client_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.client')),
                ('global_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_file_position', to='menu.file')),
            ],
        ),
    ]
