# Generated by Django 5.2.5 on 2025-08-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_localfileposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
